[package]
name = "chromium"
description = "Helps add some stability to your metal!"
version = "0.0.1-alpha"
authors = ["Lokathor <zefria@gmail.com>"]
repository = "https://github.com/Lokathor/chromium"
edition = "2018"
license = "Zlib"

[dependencies]
