name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Display Versions
      run: cargo --version && rustc --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
