name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Display Versions
      run: cargo --version && rustc --version
    - name: Stable Build
      run: cargo build --verbose
    - name: Stable Tests
      run: cargo test --verbose
    - name: Nightly Miri Tests
      run: |
        rustup default nightly
        rustup component add miri
        cargo miri setup
        cargo miri test --verbose --no-default-features
        cargo miri test --verbose
        cargo miri test --verbose --all-features
