name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Display Versions
      run: cargo --version && rustc --version
    - name: Build
      run: cargo build --verbose
    - name: Run standard tests
      run: cargo test --verbose
    - name: Run miri tests
      run: |
        rustup component add miri
        cargo miri setup
        cargo miri test --verbose --no-default-features
        cargo miri test --verbose
        cargo miri test --verbose --all-features
